import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'kwon37xi' at '13. 8. 17 오후 3:53' with Gradle 1.7
 *
 * @author kwon37xi, @date 13. 8. 17 오후 3:53
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testAdd() {
        Library library = new Library();
        assertEquals("add 5 and 2 should return 7", library.add(5, 2), 7);
    }
}
