/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'kwon37xi' at '13. 8. 17 오후 3:53' with Gradle 1.7
 *
 * @author kwon37xi, @date 13. 8. 17 오후 3:53
 */
public class Library {
    public static void main(String[] args) {
        System.out.println("Gradle아 안녕?");
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
